#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# panel
~/.config/polybar/launch.sh &

# background changer
variety &

# xrandr
xrandr --output eDP1 --panning 1600x900 --scale 1.171x1.171

# compton
compton &

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 10
bspc config border_width 1

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
