#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
killall "sxhkd"
sxhkd &

# panel
killall "polybar"
~/.config/polybar/launch.sh &

# background changer
killall "variety"
variety &

# xrandr
xrandr --output eDP1 --panning 1600x900 --scale 1.171x1.171

# compton
killall "picom"
picom &

# Set some bsp specific stuff
bspc monitor -d 1 2 3 4 5 6 7 8
bspc monitor DP1 -d 9 10


bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 10
bspc config border_width 2

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config active_border_color "#ffffff"
bspc config normal_border_color "#37474f"
bspc config focused_border_color "#e5d7c5"

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#bspc rule -a Chromium desktop='^1' focus=on
#bspc rule -a Alacritty desktop='^2' focus=on follow=on
bspc rule -a mpv state=fullscreen

